GET http://localhost:8080/books
###

POST http://localhost:8080/books
Content-Type: application/json

{
    "id": "4",
    "title": "TheGod father",
    "author": "Mario Puzo"
}

###

DELETE http://localhost:8080/books/2